name: CI
on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  build:
    name: "CI"
    uses: ./.github/workflows/build.yml
    with:
      git-ref: ${{ github.ref }}

  check:
    name: "Clang-Tidy"
    uses: ./.github/workflows/clangtidy.yml
    with:
      git-ref: ${{ github.ref }}

